export const ROUTES = {
  LOGIN: '/login',
  PROFILE: '/profile',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_USERS: '/admin/users',
  ADMIN_USERS_NEW: '/admin/users/new',
  ADMIN_USERS_EDIT: '/admin/users/:id/edit',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_PRODUCTS_NEW: '/admin/products/new',
  ADMIN_PRODUCTS_EDIT: '/admin/products/:id/edit',
  ADMIN_INGREDIENTS: '/admin/ingredients',
  ADMIN_INGREDIENTS_NEW: '/admin/ingredients/new',
  ADMIN_INGREDIENTS_EDIT: '/admin/ingredients/:id/edit',
  ADMIN_STOCK: '/admin/stock',
  ADMIN_STOCK_TRANSACTIONS: '/admin/stock/transactions',
  ADMIN_RECIPES: '/admin/recipes',
  ADMIN_RECIPES_NEW: '/admin/recipes/new',
  ADMIN_RECIPES_EDIT: '/admin/recipes/:id/edit',
  ADMIN_REPORTS: '/admin/reports',
  STAFF_POS: '/staff/pos',
  STAFF_KDS: '/staff/kds',
  STAFF_ORDERS: '/staff/orders',
  STAFF_ORDERS_DETAIL: '/staff/orders/:id',
};
